### PR TITLE
Fix column header responsiveness bug.

### LINKED ISSUE #3: Fix the 'Climate Cabinet Score' column title loading on mobile.
**expected**: When the search results load on a mobile device, the column reporting scores should be titled "CC Scores."

**current**: When the search results load on a mobile device, the column reporting scores is titled "Climate Cabinet Scores."

**steps to reproduce**:
1. Visit the main search module page on a mobile device.
2. Select a state and allow the search results to load.

**specifications**
Device: mobile
Browser: Chrome, Safari, Firefox

### PR DESCRIPTION
**Pull request by mherrero347**
When the search app was loading on mobile, the columns were not loading with their correct initial value. Specifically, the column containing scores was loading in as "Climate Cabinet Score" instead of "CC Score" as desired. The function `formatTableForBrowserSize` was refactor to make this fix.

### CODE REVIEW

File: scripts/main-built.js [hunk 1]
```diff
@@ -154,23 +154,24 @@ function refreshLegislatorFilters() {
...
-      $('#election-header').html('LAST PRES. RESULT');
-      $('.district-cell, .election-cell').show();
-      $('.results-cell > p:nth-child(2)').hide();
-      $('button.results-cell').html('TAKE ACTION');
-    } else {
-      $('#score-header').html('CLIMATE CABINET SCORE');
-      $('#election-header').html('LAST PRESIDENTIAL RESULT');
-    }
+  // apply small breakpoint changes
+  if($(window).width() <= SMALL_BREAKPOINT){
```
Comment (mcchang) [inline scripts/main-built.js:158]: oh man, we really should be building things with a JS framework and a style system that handles breakpoints for us

**Review by mcchang — APPROVED** [review]

File: scripts/main-built.js (hunk 1 above)
Comment (mherrero347) [reply scripts/main-built.js:158]: very much agree
